  
# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'ReactTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTAnimation'
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RCTCallDetection', :path => '../node_modules/react-native-call-detection'

  pod 'PingTest', :path => '../node_modules/react-native-ping-test'

  pod 'SweeprCloud', :path => '../node_modules/react-native-sweepr-cloud'

  pod 'SweeprResolution', :path => '../node_modules/react-native-sweepr-resolution'

  pod 'SweeprScan', :path => '../node_modules/react-native-sweepr-scan'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end


